### ISSUE TITLE
Invalid cron expression

### ISSUE THREAD

**Issue by virtualsheep** [Aterfax/pbs-client-docker#3]
Unable to pass regex with the default example .env CRON_SCHEDULE. Untested any more than that.

```
[cron-backup] 2024-04-28 18:33:50 Invalid cron expression: "0 */4 * * *" 
[cron-backup] 2024-04-28 18:33:50 Please define a valid cron time expression for CRON_SCHEDULE, e.g. "*/5 * * * *" as defined by https://regex101.com/r/oGYmrm/1
```

**Comment by Aterfax** [comment]
Unable to replicate on my test machine.

Please supply your .env file verbatim, as in upload it (minus any sensitive lines). You may be passing invisible invalid characters which could cause this issue.

**Comment by Aterfax** [comment]
I have just updated some the repo to also perform some additional rudimentary checks for the CRON validaton function: 

https://github.com/Aterfax/pbs-client-docker/pull/4

This is [currently passing](https://github.com/Aterfax/pbs-client-docker/actions/runs/8868573505/job/24348293572?pr=4) as expected with `0 */4 * * *`

**Comment by virtualsheep** [comment]
Confirming invalid.
K8s user returning to experiment one again with docker swarm with Portainer deployment.

```dockerfile
# The 4 variables below are required.
PBS_ENCRYPTION_PASSWORD="123456789abcdefghijklmn"
PBS_ENDPOINT="172.16.2.101"
PBS_DATASTORE="store-archive"
CRON_SCHEDULE="0 */4 * * *"

# If you want to skip backup on startup, set CRON_BACKUP_ONLY=1 otherwise CRON_BACKUP_ONLY=0
CRON_BACKUP_ONLY=1

# Use of the PBS_API_KEY_NAME and PBS_API_KEY_SECRET is recommended!
# If unset, ensure PBS_USER and PBS_PASSWORD are set.
PBS_API_KEY_NAME="docker@pbs!docker"
PBS_API_KEY_SECRET="########-####-####-####-########"

# PBS_USER is not required if PBS_API_KEY_NAME is set.
# PBS_PASSWORD is not required if PBS_API_KEY_SECRET is set.
#PBS_USER=""
#PBS_PASSWORD=""

# PBS_DATASTORE_NS is optional but should be set if using namespaces.
PBS_DATASTORE_NS="docker"

# PBS_FINGERPRINT is required if using a self signed SSL certificate.
PBS_FINGERPRINT="###REDACTED###"

TZ="Australia/Adelaide"
``` 

A big giveaway was the following log snippet:
`[backup] 2024-04-29 09:00:35 # "docker@pbs!docker"@"172.16.2.101":"store-archive"`

It would appear that in my deployment using Portainer on docker swarm treats quotation marks as part of the literal string and should not be used - this is not a pbs-client-docker issue (more likely PEBKAC - lol).

Closing!

Thanks

**Comment by Aterfax** [comment]
Thanks for letting me know! Sounds like that would have caught me out also.

I might add a specific catch for that.
